"""Initial migration

Revision ID: 55c7d01eaf0f
Revises: 65a9fe1fd433
Create Date: 2026-06-25 12:50:33.060767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c7d01eaf0f'
down_revision = '65a9fe1fd433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
