"""Initial migration

Revision ID: 65a9fe1fd433
Revises: 
Create Date: 2026-06-25 12:50:18.176489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a9fe1fd433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.BigInteger(), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('broker', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual', sa.String(length=255), nullable=True),
    sa.Column('forecast', sa.String(length=255), nullable=True),
    sa.Column('previous', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_events_id'), 'news_events', ['id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.Column('point', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('free_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('margin_level', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_id'), 'account_snapshots', ['id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=255), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_trade_duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_id'), 'backtests', ['id'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('tick_volume', sa.BigInteger(), nullable=True),
    sa.Column('spread', sa.Integer(), nullable=True),
    sa.Column('real_volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'time', name='_symbol_timeframe_time_uc')
    )
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    op.create_table('risk_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_position_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_open_positions', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_limits_id'), 'risk_limits', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('strategy_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('selected_strategy', sa.String(length=255), nullable=True),
    sa.Column('risk_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_daily_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_weekly_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lot_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_open_trades', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('is_bot_active', sa.Boolean(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('safety_mode', sa.Boolean(), nullable=True),
    sa.Column('schedule_timeframe', sa.String(length=20), nullable=True),
    sa.Column('trailing_stop_enabled', sa.Boolean(), nullable=True),
    sa.Column('trailing_stop_pips', sa.Integer(), nullable=True),
    sa.Column('breakeven_enabled', sa.Boolean(), nullable=True),
    sa.Column('breakeven_pips', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_configs_id'), 'strategy_configs', ['id'], unique=False)
    op.create_table('strategy_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=255), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('performance_metrics', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_results_id'), 'strategy_results', ['id'], unique=False)
    op.create_table('ticks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('ask', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('last', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('volume_real', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticks_id'), 'ticks', ['id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profit_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mt5_ticket', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('sl', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('tp', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_ticket')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mt5_ticket', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sl', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('tp', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('swap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_ticket')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_ticks_id'), table_name='ticks')
    op.drop_table('ticks')
    op.drop_index(op.f('ix_strategy_results_id'), table_name='strategy_results')
    op.drop_table('strategy_results')
    op.drop_index(op.f('ix_strategy_configs_id'), table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_risk_limits_id'), table_name='risk_limits')
    op.drop_table('risk_limits')
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_backtests_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_account_snapshots_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_news_events_id'), table_name='news_events')
    op.drop_table('news_events')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
